=== tiglate/Curupira/Curupira.AppClient/Config/backup-plugin.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://ampliar.dev.br/projects/curupira/plugin/backup-plugin"
           xmlns="http://ampliar.dev.br/projects/curupira/plugin/backup-plugin"
           elementFormDefault="qualified">

    <xs:element name="plugin">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="settings">
                    <xs:complexType>
                        <xs:attribute name="destination" type="xs:string" use="required" />
                        <xs:attribute name="limit" type="xs:positiveInteger" use="optional" />
                    </xs:complexType>
                </xs:element>
                <xs:element name="backups">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="backup" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="remove" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:string" use="required" />
                                    <xs:attribute name="root" type="xs:string" use="required" />
                                </xs:complexType>
                                <xs:unique name="uniqueBackupId">
                                    <xs:selector xpath="." />
                                    <xs:field xpath="@id" />
                                </xs:unique>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== tiglate/Curupira/Curupira.WindowsService/Config/backup-plugin.xml
<?xml version="1.0" encoding="UTF-8" ?>
<plugin xmlns="http://ampliar.dev.br/projects/curupira/plugin/backup-plugin"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://ampliar.dev.br/projects/curupira/plugin/backup-plugin backup-plugin.xsd">
    <settings destination="c:\temp" limit="3" />
    <backups>
        <backup id="ruby" root="C:\Ruby">
            <remove>bin</remove>
            <remove>etc</remove>
            <remove>include\</remove>
            <remove>lib\</remove>
            <remove>msys64</remove>
            <remove>packages\*</remove>
            <remove>**\*.html</remove>
            <remove>LICENSE.txt</remove>
        </backup>
        <backup id="dell" root="C:\Dell\Drivers\HFVP5\EULA" destination="P:\temp">
        </backup>
        <backup id="xampp" root="C:\xampp\cgi-bin">
            <remove>*.pl</remove>
        </backup>
        <backup id="tomcat" root="C:\tomcat" />
    </backups>
</plugin>

=== tiglate/Curupira/Curupira.AppClient/Config/backup-plugin.xml
<?xml version="1.0" encoding="UTF-8" ?>
<plugin xmlns="http://ampliar.dev.br/projects/curupira/plugin/backup-plugin"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://ampliar.dev.br/projects/curupira/plugin/backup-plugin backup-plugin.xsd">
  <settings destination="c:\temp" limit="3" />
  <backups>
    <backup id="ruby" root="C:\Ruby">
      <!--
      <remove>lib</remove>
      <remove>msys64</remove>
      <remove>share</remove>
      <remove>*.txt</remove>
      -->
      <remove>bin</remove>
      <remove>etc\ssl\certs</remove>
      
      <remove>include</remove>
      <remove>*.txt</remove>
      <remove>msys64</remove>
      <remove>ridk_use</remove>
      <remove>share\doc\ruby\html\*.html</remove>
      <remove>unins000.dat</remove>
      <remove>unins000.exe</remove>
    </backup>
    <backup id="dell" root="C:\Dell\Drivers\HFVP5\EULA">
    </backup>
    <backup id="xampp" root="C:\xampp\cgi-bin">
      <remove>*.pl</remove>
    </backup>
  </backups>
</plugin>
