=== tiglate/Curupira/Curupira.AppClient/Config/installer-plugin.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://ampliar.dev.br/projects/curupira/plugin/installer-plugin"
           xmlns="http://ampliar.dev.br/projects/curupira/plugin/installer-plugin"
           elementFormDefault="qualified"
           attributeFormDefault="unqualified">

    <!-- Root element definition -->
    <xs:element name="plugin">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="components">
                    <xs:complexType>
                        <xs:sequence>
                            <!-- One or more components allowed -->
                            <xs:element name="component" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <!-- One or more params allowed -->
                                        <xs:element name="param" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:attribute name="name" type="xs:string" use="required"/>
                                                <xs:attribute name="value" type="xs:string" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <!-- Attributes for component -->
                                    <xs:attribute name="id" type="xs:string" use="required"/>
                                    <xs:attribute name="type" use="required">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="zip"/>
                                                <xs:enumeration value="msi"/>
                                                <xs:enumeration value="bat"/>
                                                <xs:enumeration value="exe"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                    <!-- Conditional action attribute for type="msi" -->
                                    <xs:attribute name="action" use="optional">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="install"/>
                                                <xs:enumeration value="uninstall"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                </xs:complexType>
                                <!-- Action attribute required only for type="msi" -->
                                <xs:unique name="uniqueParamName">
                                    <xs:selector xpath="param"/>
                                    <xs:field xpath="@name"/>
                                </xs:unique>
                                <!-- Unique id constraint for component -->
                                <xs:unique name="uniqueComponentId">
                                    <xs:selector xpath="component"/>
                                    <xs:field xpath="@id"/>
                                </xs:unique>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== tiglate/Curupira/Curupira.WindowsService/Config/installer-plugin.xml
<?xml version="1.0" encoding="utf-8" ?>
<plugin xmlns="http://ampliar.dev.br/projects/curupira/plugin/installer-plugin"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://ampliar.dev.br/projects/curupira/plugin/installer-plugin installer-plugin.xsd">
    <components>
        <component id="ruby" type="zip">
            <param name="SourceFile" value="C:\temp\ruby.zip" />
            <param name="TargetDir" value="P:\Ruby" />
            <remove>include\ruby-3.2.0\ruby.h</remove>
            <remove>include\ruby-3.2.0\ruby\io\*</remove>
        </component>
        <component id="InstallAppTest" type="msi" action="install">
            <param name="SourceFile" value="C:\temp\AppTeste.msi" />
            <param name="Params" value="/qn" />
        </component>
        <component id="Install.bat" type="bat">
            <param name="SourceFile" value="C:\temp\Install.bat" />
            <param name="Params" value="C:\temp\myapp" />
        </component>
        <component id="Installer.exe" type="exe">
            <param name="SourceFile" value="C:\temp\Installer.exe" />
            <param name="Params" value="C:\temp\myapp2" />
        </component>
    </components>
</plugin>
