=== tiglate/Curupira/Curupira.AppClient/Config/service-manager-plugin.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://curupira.org/plugin/service-manager-plugin"
           xmlns="http://curupira.org/plugin/service-manager-plugin"
           elementFormDefault="qualified"
           attributeFormDefault="unqualified">
    <xs:element name="plugin">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="bundles">
                    <xs:complexType>
                        <xs:sequence>
                            <!-- One or more bundles required -->
                            <xs:element name="bundle" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <!-- One or more services required -->
                                        <xs:element name="service" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:attribute name="name" type="xs:string" use="required"/>
                                                <xs:attribute name="action" use="required">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:string">
                                                            <xs:enumeration value="Start"/>
                                                            <xs:enumeration value="Stop"/>
                                                        </xs:restriction>
                                                    </xs:simpleType>
                                                </xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>

                    <!-- Unique constraint on bundle id -->
                    <xs:unique name="uniqueBundleId">
                        <xs:selector xpath="bundle"/>
                        <xs:field xpath="@id"/>
                    </xs:unique>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== tiglate/Curupira/Curupira.AppClient/Config/service-manager-plugin.xml
<?xml version="1.0" encoding="utf-8" ?>
<plugin xmlns="http://curupira.org/plugin/service-manager-plugin"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://curupira.org/plugin/service-manager-plugin service-manager-plugin.xsd">
    <bundles>
        <bundle id="stop_all">
            <service name="WSearch" action="Stop" />
            <service name="wuauserv" action="Stop" />
        </bundle>
        <bundle id="start_all">
            <service name="WSearch" action="Start" />
            <service name="wuauserv" action="Start" />
        </bundle>
    </bundles>
</plugin>
